#include "quadruped.h"

#define TAG "QuadBase"

void quad_init(void)
{
  //初始化舵机
  servo_set_freq(CONFIG_SERVO_PWM_FREQ);
  //初始化 ACB
  leg_sync_acb_init(CONFIG_ACB_DEFAULT_EASING_CALC);
  //初始化 CCB
  leg_sync_ccb_init(CONFIG_CCB_DEFAULT_EASING_CALC_X, CONFIG_CCB_DEFAULT_EASING_CALC_Z);
  //初始化舵机位置
  leg_sync_set_coord(cc_stand0);

  elog_i(TAG, "Quad Init Success:");
  elog_i(TAG, "%-14s: %-07.3f", "Servo Freq" ,CONFIG_SERVO_PWM_FREQ);
  elog_i(TAG, "%-14s: RF[%-07.3f,%-07.3f] LF[%-07.3f,%-07.3f] RB[%-07.3f,%-07.3f] LB[%-07.3f,%-07.3f]", "Servo Offset",
    CONFIG_SERVO_OFFSET_RF_T, CONFIG_SERVO_OFFSET_RF_S,
    CONFIG_SERVO_OFFSET_LF_T, CONFIG_SERVO_OFFSET_LF_S,
    CONFIG_SERVO_OFFSET_RB_T, CONFIG_SERVO_OFFSET_RB_S,
    CONFIG_SERVO_OFFSET_LB_T, CONFIG_SERVO_OFFSET_LB_S);
  elog_i(TAG, "%-14s: RF[%-07.3f,%-07.3f] LF[%-07.3f,%-07.3f] RB[%-07.3f,%-07.3f] LB[%-07.3f,%-07.3f]", "Servo Limit",
    CONFIG_SERVO_LIMIT_MIN_T, CONFIG_SERVO_LIMIT_MAX_T,
    CONFIG_SERVO_LIMIT_MIN_S, CONFIG_SERVO_LIMIT_MAX_S,
    CONFIG_SERVO_LIMIT_MIN_T, CONFIG_SERVO_LIMIT_MAX_T,
    CONFIG_SERVO_LIMIT_MIN_S, CONFIG_SERVO_LIMIT_MAX_S);
  elog_i(TAG, "%-14s: RF[%-07.3f,%-07.3f] LF[%-07.3f,%-07.3f] RB[%-07.3f,%-07.3f] LB[%-07.3f,%-07.3f]", "Coord Offset",
    CONFIG_LEG_COORD_OFFSET_X_RF, CONFIG_LEG_COORD_OFFSET_Z_RF,
    CONFIG_LEG_COORD_OFFSET_X_LF, CONFIG_LEG_COORD_OFFSET_Z_LF,
    CONFIG_LEG_COORD_OFFSET_X_RB, CONFIG_LEG_COORD_OFFSET_Z_RB,
    CONFIG_LEG_COORD_OFFSET_X_LB, CONFIG_LEG_COORD_OFFSET_Z_LB);
}